### ISSUE TITLE
Email credentials does not work

### ISSUE THREAD

**Issue by freddycoder** [freddycoder/ErabliereApi#192]
Environnement: Prod
Url: erabliereapi.freddycoder.com

```
ErabliereApi.Controllers.Attributes.TriggerAlertAttribute[92837486]
      Une erreur imprévue est survenu lors de l'envoie de l'alerte.
      MailKit.Security.AuthenticationException: 535: 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [YQBPR01CA0046.CANPRD01.PROD.OUTLOOK.COM 2023-09-26T11:30:13.970Z 08DBBC72C1B3D65F]
       ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [YQBPR01CA0046.CANPRD01.PROD.OUTLOOK.COM 2023-09-26T11:30:13.970Z 08DBBC72C1B3D65F]
         --- End of inner exception stack trace ---
         at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
         at ErabliereApi.Controllers.Attributes.TriggerAlertV2Attribute.TriggerAlerte(AlerteCapteur alerte, ILogger`1 logger, EmailConfig emailConfig) in /app/ErabliereApi/Attributes/TriggerAlertAttributeV2.cs:line 149
```

**Comment by freddycoder** [comment]
This is caused by the MFA Enable for all accounts. Should not be a problem for other deployments that the configuration hasn't changed. 

OAuth and Microsoft Graph implementation is in progress.

**Comment by freddycoder** [comment]
https://github.com/freddycoder/ErabliereApi/pull/199

**Comment by freddycoder** [comment]
Next is to change the Email config file to use the new method. After the alert fonctionnaity will work again.

**Comment by freddycoder** [comment]
Now working, this issue will be closed, but I discovered an issue in logic on the trigger alert. Will be documented and fixed in another issue
